/**
 * Norsk Nettverk v2 — Norwegian strings.
 * Mirror this to `en.ts` later if English support is added.
 */
export const strings = {
  brand: "NORSK NETTVERK",
  search: {
    placeholder: "Søk politikere eller selskaper...",
  },
  tabs: {
    dashboard: "Dashboard",
    network: "Nettverk",
    directory: "Katalog",
    alerts: "Varsler",
  },
  dashboard: {
    intelligenceHeading: "Global intelligence",
    investigations: "Undersøkelser",
    revolvingDoor: "Roterende dør",
    activeAlerts: "Aktive varsler",
    revolvingDoorFeed: "Roterende dør — siste hendelser",
    highConflict: "Høyeste konfliktnivå",
    sectorWatchlist: "Sektor-overvåking",
    newCases: "Nye saker",
    analyze: "Analyser",
    deltaVsLastMonth: "vs. forrige måned",
    badgeRevolvingDoor: "ROTERENDE DØR",
    badgePotentialConflict: "POTENSIELL KONFLIKT",
    emptyFeed: "Ingen overganger funnet.",
    emptyRanking: "Ingen konfliktdata tilgjengelig.",
    partialDataWarning: "Noen datakilder er midlertidig utilgjengelige.",
    sources: "Kilder",
  },
  network: {
    title: "Nettverkskart",
    legend: "Tegnforklaring",
    liveFeed: "LIVE-UNDERSØKELSE",
    filter: {
      all: "Alle",
      energy: "Energi",
      parliament: "Storting",
      lobby: "Lobby",
    },
  },
  directory: {
    title: "Katalog",
    subtitle:
      "Overvåk forbindelser mellom folkevalgte og næringsliv. Spor karrieretrekk og potensielle interessekonflikter.",
    sortByName: "Navn: A–Z",
    sortByConflict: "Konfliktnivå",
    sortByConnections: "Flest forbindelser",
    sortByRecent: "Nylig aktivitet",
    loadMore: "Last flere profiler",
    badgeRevolvingRisk: "ROTERENDE DØR",
    badgeClean: "REN PROFIL",
    badgeDisclosure: "TRENGER REGISTRERING",
    badgeKarantene: "KARANTENESAK",
    badgeActiveConflict: "AKTIV KONFLIKT",
    filterAll: "Alle",
    filterPoliticians: "Politikere",
    filterBoard: "Styreverv",
    filterKarantene: "Karantene",
    filterConflicts: "Konflikter",
    countLabel: "treff",
    noResults: "Ingen profiler matcher søket.",
    connectionsLabel: "forbindelser",
    boardLabel: "verv",
    karanteneLabel: "karantenesaker",
    searchPlaceholder: "Søk navn, organisasjon eller parti…",
    sortLabel: "Sortér",
  },
  alerts: {
    title: "Varsler",
    subtitle: "Live-feed av nyere overganger og karantenesaker.",
    watchlistTitle: "Overvåking",
    watchlistEmpty: "Du følger ikke noen profiler ennå.",
    watchlistHint: "Åpne en profil og trykk «Følg» for å få et eget felt her.",
    addToWatchlist: "Følg",
    removeFromWatchlist: "Slutt å følge",
    matchingAlerts: "treff i feeden",
    noNewAlerts: "Ingen nye varsler",
    feedTitle: "Hendelser",
    feedEmpty: "Ingen registrerte hendelser akkurat nå.",
    openPdf: "Åpne PDF",
    badgeKarantene: "KARANTENE",
    badgeRevolving: "ROTERENDE DØR",
    badgeConflict: "INTERESSEKONFLIKT",
  },
  profile: {
    conflictScore: "Konfliktnivå",
    conflictScoreIndex: "Konfliktindeks",
    connections: "Forbindelser",
    tenure: "Tjenestetid",
    boards: "Styreverv",
    pastRoles: "Tidligere roller",
    careerTrajectory: "Karriereforløp",
    knownConnections: "Kjente forbindelser",
    karantene: "Karantenenemnda",
    karanteneSubtitle: "Avgjørelser fra Karantenenemnda etter overgang fra politisk verv.",
    backToDashboard: "← Tilbake",
    publicLabel: "Offentlig",
    privateLabel: "Privat",
    politicalLabel: "Politisk",
    governmentLabel: "Regjering",
    boardLabel: "Styre",
    executiveLabel: "Leder",
    revolvingDoorGap: "Svingdør",
    days: "dager",
    present: "Nåværende",
    conflictsOfInterest: "Interessekonflikter",
    noConflicts: "Ingen registrerte konflikter.",
    noKarantene: "Ingen karantenesaker registrert.",
    notFound: "Fant ikke profilen.",
    riskHigh: "Høy risiko for svingdør oppdaget",
    riskMedium: "Moderat risiko for svingdør",
    riskLow: "Lav konfliktrisiko",
    party: "Parti",
    fylke: "Fylke",
    viewPdf: "Åpne PDF",
    classification: "Klassifisering",
  },
  common: {
    backToOverview: "Tilbake til oversikt",
    loading: "Laster…",
    error: "Noe gikk galt",
    retry: "Prøv igjen",
  },
};

export type Strings = typeof strings;
